DROP TABLE BI_JUS.JUS_DIM_SD_DATA_MES_12A CASCADE CONSTRAINTS;

CREATE TABLE BI_JUS.JUS_DIM_SD_DATA_MES_12A
( 
	COD_12A	NUMBER(6),
	COD_ANY_MES	NUMBER(6),
	BAIXA_LOGICA	NUMBER(1),
	SISTEMA	VARCHAR2(1),
	ID_CARREGA	NUMBER(18),
	DATA_ACT	TIMESTAMP(6)
)
TABLESPACE BI_JUS_DIM_STG_DAT
NOLOGGING
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

GRANT SELECT, DELETE, INSERT, UPDATE ON BI_JUS.JUS_DIM_SD_DATA_MES_12A TO  BI_JUS_APLIC_ROLE;
GRANT SELECT ON BI_JUS.JUS_DIM_SD_DATA_MES_12A TO BI_JUS_CONS_ROLE;


DROP TABLE BI_JUS.JUS_DIM_DD_DATA_MES_12A CASCADE CONSTRAINTS PURGE;

CREATE TABLE BI_JUS.JUS_DIM_DD_DATA_MES_12A
( 
	SKU_ANY_MES NUMBER(18),
	COD_ANY_MES	NUMBER(6),
	SKU_12A	NUMBER(18),
	COD_12A	NUMBER(6),
	BAIXA_LOGICA 	NUMBER(1)	DEFAULT 0,
	SISTEMA	VARCHAR2(1)	DEFAULT 'N',
	ID_CARREGA	NUMBER(18),
	DATA_ACT	TIMESTAMP(6),
	CONSTRAINT UK_JUS_DIM_DD_DATA_MES_12A_PK PRIMARY KEY (SKU_ANY_MES,SKU_12A)
)
TABLESPACE BI_JUS_DIM_DDS_DAT
NOLOGGING
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

--CREATE BITMAP INDEX  BI_JUS.JUS_IDX_DIM_DD_DATA_MES_1 ON BI_JUS.JUS_DIM_DD_DATA_MES_12A (COD) LOGGING TABLESPACE BI_JUS_DIM_DDS_IDX NOPARALLEL;

GRANT SELECT, DELETE, INSERT, UPDATE ON BI_JUS.JUS_DIM_DD_DATA_MES_12A TO BI_JUS_APLIC_ROLE;

GRANT SELECT ON      BI_JUS.JUS_DIM_DD_DATA_MES_12A TO BI_JUS_CONS_ROLE;

declare
  cod2 number(6);
begin

for x in (select sku from BI_JUS.jus_dim_DD_DATA_MES where  cod_any_mes > 1000 order by cod_any_mes) loop
  for i in 0..11 loop
    cod2 := to_number(to_char(add_months(to_date(to_char(x.sku),'yyyymm'),-i),'yyyymm'));
  --  dbms_output.put_line(x.sku||' - '||cod2);
  BEGIN
INSERT INTO  BI_JUS.JUS_DIM_SD_DATA_MES_12A	(COD_ANY_MES,COD_12A,BAIXA_LOGICA,SISTEMA,ID_CARREGA,DATA_ACT) VALUES
(x.sku,cod2,0,'N',1,SYSDATE);
	  END;
  end loop;

end loop;

end;
